// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ybtxcdkkncjwxomujzal.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InlidHhjZGtrbmNqd3hvbXVqemFsIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTI5ODczNTUsImV4cCI6MjA2ODU2MzM1NX0.Pwi7wzTsu0fiq23PGSWL6sEr9s9tjSVYtVuRbvPMuXM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});